[package]
name = "botcoins-db"
version = "0.1.0"
authors = ["ConcurrentMarxistGC <concurrentmarxistgc@users.noreply.github.com>"]

[dependencies]
rocket = "0.3.10"
rocket_codegen = "0.3.10"
lazy_static="*"
